### ISSUE TITLE
Configure CI/CD azure pipeline

### ISSUE THREAD

**Issue by Letslearnxamarin** [Letslearnxamarin/Pinterest-net-wrapper#6]
Using Azure Pipelines to run Builds and Unit Tests against build.

Also Use build to push updated Client to Nuget
- [x] Pushed Nuget Package
- [x] Runs Build
- [x] Runs Unit Tests
- [x] Push Docker Image

**Comment by comradelemoncake** [comment]
Assign me this! I got this.

**Comment by Letslearnxamarin** [comment]
Thanks for the offer, but I think I am going to do this one.
